server:
  port: 8080

  servlet:
    jsp:
      init-parameters: 
        development: true 
    session:
      timeout: 7200
  error:
    whitelabel:
      enabled: false
---
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    static-path-pattern: /resources/** 

---
spring:   
  datasource:
    hikari:
      driverClassName: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://192.168.0.136:3306/armtong_proj
      username: stack
      password: stack